In [1]:
import numpy as np
from sklearn.mixture import GaussianMixture

In [26]:
gmm = GaussianMixture(n_components=2, covariance_type='full')
# Define means and covariances
mu_1 = np.array([0.75, 0.25])
mu_2 = np.array([0.25, 0.75])

cov_1 = np.array([[0.3, 0.0], 
                  [0.0, 0.1]])

cov_2 = np.array([[0.2, 0.05], 
                  [0.05, 0.1]])

# Number of samples from each distribution
n_samples = 1000
n_samples_per_dist = n_samples // 2

# Generate samples
samples_1 = np.random.multivariate_normal(mu_1, cov_1, n_samples_per_dist)
samples_2 = np.random.multivariate_normal(mu_2, cov_2, n_samples_per_dist)

# Combine and shuffle samples
samples = np.vstack((samples_1, samples_2))
np.random.shuffle(samples)

# Verify the shape of the samples matrix
# print("Shape of samples matrix:", samples.shape)

# # Display the first 5 samples
# print("First 5 samples:\n", samples[:5])


In [27]:
print("First 5 samples:\n", samples[:5])

First 5 samples:
 [[ 0.7534742   0.41767802]
 [ 1.0190615   0.41387336]
 [-0.1881834  -0.01588411]
 [ 1.43298316  0.32517327]
 [ 0.37241549  0.71890031]]


In [35]:
fitted_gmm = gmm.fit(samples)

cluster_centres = fitted_gmm.means_

cluster_covs = fitted_gmm.covariances_

In [36]:
cluster_centres

# real centres

# mu_1 = np.array([0.75, 0.25])
# mu_2 = np.array([0.25, 0.75])

μ_1 = [0.1874289 , 0.61428045] 

μ_2 = [0.8446443 , 0.33405549]

array([[0.1874289 , 0.61428045],
       [0.8446443 , 0.33405549]])

In [37]:
cluster_covs

# real covs

# cov_1 = np.array([[0.3, 0.0], 
#                   [0.0, 0.1]])

# cov_2 = np.array([[0.2, 0.05], 
#                   [0.05, 0.1]])

cov_1 = [[ 0.17083841,  0.02823075],
        [ 0.02823075,  0.13377022]]

cov_2 = [[ 0.21618161, -0.00799517],
        [-0.00799517,  0.1442702 ]]

array([[[ 0.17083841,  0.02823075],
        [ 0.02823075,  0.13377022]],

       [[ 0.21618161, -0.00799517],
        [-0.00799517,  0.1442702 ]]])